### ISSUE TITLE
Create new page for Privacy policy, so that we can have the facebook connect

### ISSUE THREAD

**Issue by adriverhagen** [barsukov/shelfless#10]
We need a privacy policy to communicate what we are doing with the user data that we are gathering.
This is also needed to make the connection between facebook app and shelfless.

we need  to create url : www.shelfless.de/privacy/

with content : 

https://docs.google.com/document/d/1W1TEIFEptOjh2QyE58aVEH0PGeocD8KDFXiq0tuyB50/edit#

**Comment by barsukov** [comment]
Good job! 
Need to integrate it with some screenshot too...

**Comment by adriverhagen** [comment]
Screenshot of the privacy policy? I don't get it. 

If you mean the screenshots of website than it will be seperate issue. This just about page for privacy policy.

**Comment by barsukov** [comment]
Yes this seperate issue, screenshots for verification "how we use facebook"
