### ISSUE TITLE
Check out Blinkist

### ISSUE THREAD

**Issue by adriverhagen** [barsukov/shelfless#14]
https://www.blinkist.com/en/library/

I like their user-back-end display.

**Comment by barsukov** [comment]
this is look very nice , but I prefer to concentrate about book swaping process instead of every day do redesign login page...

**Comment by adriverhagen** [comment]
Hey, redesign login page is not necessary. I think you misunderstood me here, but i will show you once we see each other. In any case, you have a valid point, first focus is get the swapping process, thats why we need a user back-end view. Lets talk about this tonight.

**Comment by barsukov** [comment]
close this @adriverhagen
