### ISSUE TITLE
As a user, i want to be able to sign up with facebook so that i can use shelfless

### ISSUE THREAD

**Issue by adriverhagen** [barsukov/shelfless#15]
Facebook connect
- [x] privacy policy 

need to create url : www.shelfless.de/privacy/
content : https://docs.google.com/document/d/1W1TEIFEptOjh2QyE58aVEH0PGeocD8KDFXiq0tuyB50/edit#
- [x] Help section

URL : www.shelfless.de/help

Conten( WIP) : https://docs.google.com/document/d/1LxILw3bZ64RPYbVBzBWnYWMQFVAnQX8dmj0snQ7xtw0/edit
- [x]  Terms

URL: www.shelfless.de/tos
Content: https://docs.google.com/document/d/1jB1mZEtJohtXRwGN5KseYNa1-lAJv1jpcw6v8x7KEUk/edit
- [x]  screenshots
- [x] logo
- [x] App Page

https://www.facebook.com/shelfless

**Comment by barsukov** [comment]
Help section is a good but , what do you think if we put some information about it, in the main page?

**Comment by barsukov** [comment]
only this ?
