### ISSUE TITLE
As a Reader, i want to be able to borrow a book from a holder, so that i can read it

### ISSUE THREAD

**Issue by adriverhagen** [barsukov/shelfless#16]
see doc https://docs.google.com/document/d/1S1yvMsxUJcvaEcMByXib0hxy0Nn3TlCvpmHWGtDoTEM/edit?usp=sharing

**Comment by barsukov** [comment]
This issue should have sub issue, mail notification after requesting and so on

**Comment by adriverhagen** [comment]
Hey i don't understand, can you explain tonight?

**Comment by barsukov** [comment]
:smiley_cat:  yeap

**Comment by barsukov** [comment]
I think I can close this issue easily
