### ISSUE TITLE
As a Holder, i want to be notified when a book time is over so  that the book status gets updated

### ISSUE THREAD

**Issue by adriverhagen** [barsukov/shelfless#17]
Reader Return

if before time
     reader and holder contact one an other
     then holder is responsible for changing the status

timer is over
     holder gets e-mail, with four options:

" Hey holder,

Times up for "Reader-name", who is currently reading your copy of " Title-Author". 

What would you like to do next? 
          1. Extend (the loan to " return date + 4 weeks" )
          2. Return (start the conversation to get your books back)
          3. Gift it ( simply give away to the reader)

Your Shelfless Team. "
1. Extend
    reader gets notification:
   "Hey "Reader-name",

your book loan got extended until the return date + 4 weeks. 

You can always initiatie the return by simply getting touch with the holder:
Holder contact.

Your Shelfless Team. "

2.Now
 holder chooses now
 reader gets notified, to start communication with holder, otherwise he gets banned.
E-Mail to Reader:
"Hey 

Time to return "Title-Author" to "Holder-name", get in touch by clicking here( hyperlink to e-mail holder).

If you need an extension, kindly request it while you get in touch.

Feel free to contact us if you have something to say.

Sharing is caring - Your Shelfless Team. "

holder has to make 

3.Gift it 
     holder chooses “gift it" 
     reader gets notified 
     reader becomes new holder
     Books comes in reader book  table

Hey ' Reader-name"

Its your lucky day :-) , "Holder-name" has gifted you "Title-Author".

Your book list has been updated, you are the new holder.

Feel free to contact "Holder-name" if you have something to say.

Sharing is caring - Your Shelfless Team "
1. Already returned 
    holder chooses “already returned"
    status of book changes automatically to available again.

**Comment by adriverhagen** [comment]
Reading list (READER), after return date is over, status update to " RETURN" ( what do you think ? )
![screen shot 2015-04-23 at 10 13 55](https://cloud.githubusercontent.com/assets/7081026/7293061/5ebe9ae0-e9a1-11e4-8fcb-847411c17bc7.png)

**Comment by barsukov** [comment]
I can put return date and remove postcode I think this is a good. Status update to renturned? I think thi a little bit different. Even in a mind, need to think about it

**Comment by barsukov** [comment]
ping!

**Comment by adriverhagen** [comment]
Update to return process :

Reader Return

if before time
reader and holder contact one an other
then holder is responsible for changing the status

timer is over
holder gets e-mail, with 2 options:

(1). Return (start the conversation to get your book back)
(2). Update Status ( already returned, update status of book to shared again)

(1). Holder requests Return

Holder chooses Return
reader gets notified, to start communication with holder, otherwise he gets banned.
Get the option to ask for an extension(3).

(2). Holder Update Status:
Already returned holder chooses “Update status", status of book changes automatically to available again.

(3) Reader asks for extension, notification sent to Holder, he can 

Accept(4) or Reject (5)?

(4): Holder accepts extension request of reader; reader gets confirmation with new date.

(5): Holder has rejected extension request of reader. Reader receives a notification telling him to get in touch with holder to return book now.

End

**Comment by barsukov** [comment]
Check this issue @adriverhagen please and test it if everything ok close , if not close this LOOONG issue and open new one.
