### ISSUE TITLE
Holder gets error message when accept book request

### ISSUE THREAD

**Issue by adriverhagen** [barsukov/shelfless#23]
accept book - bug

incoming request ---> new request --> choose accept/decline --> choose decline, error.

http://shelfless.de/accounts/1/holder_book_requests/12?book_id=5

**Comment by barsukov** [comment]
FIXED

**Comment by adriverhagen** [comment]
appears again

**Comment by adriverhagen** [comment]
same problems when accept request from email, get an error message.

**Comment by adriverhagen** [comment]
only for accept

**Comment by barsukov** [comment]
try again
