### ISSUE TITLE
GIFTING: As a Holder, i want to be able to gift a book to a reader so that i can close my transaction

### ISSUE THREAD

**Issue by adriverhagen** [barsukov/shelfless#25]
A book gets a new holder, when the current holder gifts the book to the reader.

After the return date, the holder receives a message where he has 3 options:
1. Extend
2. Initiate Return
3. Gift it

Upon choosing gift it, the book changes holder.
The new holder is the current reader.
The book comes in the "My books" of the current reader
The book get deleted from "my books" of current holder and from the " Reading list" of the current Reader.

**Comment by barsukov** [comment]
Nice job, I will go to the gifting ASAP after finish normal process
