### ISSUE TITLE
Error when log out

### ISSUE THREAD

**Issue by adriverhagen** [barsukov/shelfless#29]
http://shelfless.de/accounts/10/holder_book_requests/54?book_id=29

I am signed as pro.verhagen@gmail.com , then i want to log out and i get error message

The change you wanted was rejected.

Maybe you tried to change something you didn't have access to.

If you are the application owner check the logs for more information.

**Comment by adriverhagen** [comment]
decided not to solve for now
no prio

**Comment by barsukov** [comment]
Solved
