### ISSUE TITLE
Landing page text

### ISSUE THREAD

**Issue by adriverhagen** [barsukov/shelfless#32]
Just 3 steps, dude:
1. Search

Search by title in the library to find your next read.
Then request(BOLD) to initiate the sharing.

The shared library contains over 600 books.

(Picture : woman hands)
1. Meet 

Set a time and date(BOLD) to meet after you’ve received a confirmation by the book owner.

Meet each other in real life (BOLD).

( Picture :  couple ) 
1. Return

4 weeks after your request you meet again to return the book to its holder.

Picture: Meet to return - catcher in the rye - book in hand

**Comment by barsukov** [comment]
Text is here , without photo wait a photo
