### ISSUE TITLE
2nd extension returns as decline

### ISSUE THREAD

**Issue by adriverhagen** [barsukov/shelfless#37]
1. ask extension once - all fine
2. ask extension 2nd time - return extension declined
   ![screen shot 2015-06-17 at 21 29 44]
   and holder receives this email : 

title : book request
(https://cloud.githubusercontent.com/assets/7081026/8216565/adf6e524-1537-11e5-8a44-375a2bfa8058.png)

**Comment by barsukov** [comment]
Is this bug occured again?

**Comment by adriverhagen** [comment]
now the user does not get possibility to extend 2 x

it tells reader to return
holder has only option to choose " already returned" :
Hey Pro Verhagen

Get in touch with Adriana Verhagen to return The art of loving

Hodler email: adriana.verhagen@gmail.com

Adriana Verhagen has requested you return it. If you need an extension, kindly request it while you get in touch.

Feel free to contact us.

**Comment by adriverhagen** [comment]
i think it is fine for now.

the e-mail of the second return has to change. ( i make separate issue for this).
Because bug decline extension not there anymore.
