### ISSUE TITLE
As an user, i want to create an account so that i can use Shelfless

### ISSUE THREAD

**Issue by adriverhagen** [barsukov/shelfless#4]

**Comment by adriverhagen** [comment]
We have to decide what type of log in approach we want to have.
We can choose between 3 Styles :
1. meet up vs 
   2.twitter style vs 
   3.craigslist.

Twitter style : 
Login/ sign up directly on homepage

PROS vs CONS
 (+) reduces a step in the overall process when borrowing abooks, because users will ony be able to acces the content once they are logged in
(-) Not showing what is in the website without log in might reduce the number of people joining

![screen shot 2015-04-06 at 18 30 39](https://cloud.githubusercontent.com/assets/7081026/7007499/d9f1fc08-dc8a-11e4-9c6d-bdfda53cf630.png)

or

Meetup style:

PROS vS CONS

![screen shot 2015-04-06 at 18 33 31](https://cloud.githubusercontent.com/assets/7081026/7007546/3a02bf10-dc8b-11e4-810b-c7bc1d340f1c.png)

Craigslist style: 
Show all, seperate login at the side(1), then redirected to login page (2)

PRO vs CONS
(+) Users can view what the content is before signing up +
(+) Using e-mail only, avoiding connection with facebook +
(-) Changeing communication channel from facebook to e-mail, right now facebook is where it happens. In  the long run i do not want to be affiliated with facebook. I am looking up to craigslist 
(1)

![screen shot 2015-04-07 at 20 05 04](https://cloud.githubusercontent.com/assets/7081026/7029975/8a5503a2-dd61-11e4-82b8-c7cd94ab013f.png)

(2) 
![screen shot 2015-04-07 at 20 05 15](https://cloud.githubusercontent.com/assets/7081026/7029942/4aae03f2-dd61-11e4-8776-81f7bf14a70f.png)

An account consists of : 
1. Name
2. E-mail
3. Password
OR
3. Facebook profile

**Comment by adriverhagen** [comment]
@barsukov could you add your pro`s and con`s for signup with meet up

**Comment by barsukov** [comment]
PRONS without registration:
1) We have more users which only currious about the platform and do not decide yet what are they want.
2) Registration is annoying when you ask in a first page
3) Even that provided by facebook, no so many people have a facebook (people who read the books prefer read the books not sitting in a facebook)

CONS
1) We do not know real statistics of how many people registered and want to use it
2) People does not seen really advantage to register if they can get it imideatly in a first page

My view: 
get a first page with about the service like temporary date and good landing page (what about this service)
and you can see the list of people (without contacts and ability to share the book)
when you register you can see everything and add the book.

**Comment by barsukov** [comment]
CLOSE
