### ISSUE TITLE
As an user, i want to get a welcoming message when i set up an account to understand how to use shelfless

### ISSUE THREAD

**Issue by adriverhagen** [barsukov/shelfless#5]
When the user creates his profile a welcoming message is shown to him or send to him ? we need to think about this.

the content : 

" Welcome to Shelfless, Berlins' community library. <3

To make shareing together easier, here some information for you.
Books are accesible to anyone from anyone.

no discrimination here!

GUIDELINES ON HOW TO USE SHELFLESS (bold):

Once you make a share/swap, please mark this in the sheet in the indicated fields.
- Add your name
- Add date your made the exchange,
- if it is a share, choose # of weeks. The row will be turned red
  automatically. This is to make it easier to know who has what book and when the book should be returned
  ![pic 1-edit fields](https://cloud.githubusercontent.com/assets/7081026/7006898/1fb789ca-dc85-11e4-9cbe-b8cd7a89ca0c.png)
- Find contact info from the book owner in the contact sheet.
  ![contact sheet](https://cloud.githubusercontent.com/assets/7081026/7006902/246f5664-dc85-11e4-8292-560bb344fc06.png)

Finally, Respect our books - Sharing is caring.  <3

If you have any questions please feel free to contact me.

Adriana (adriana.verhagen@gmail.com)

http://bit.ly/Shelfless

**Comment by barsukov** [comment]
Almost done need to write normal wellcome message for the site recreate another issue for mail message
