### ISSUE TITLE
As a user, i want to land on shelfless.de and know what the service is about so that i will use it

### ISSUE THREAD

**Issue by adriverhagen** [barsukov/shelfless#6]
Landing on www.shelfless.de

Components : 
1. welcoming message
2. login or signup
1. Welcoming message : 

" Welcome to Shelfless.

Share Books - lend, borrow or swap them.  Connect with book-lovers and
find out what your neighborhood is reading. "

3 .LOGIN or SIGNUP do like twitter:
one box login
one box sign up

layout : 
![screen shot 2015-04-07 at 19 44 51](https://cloud.githubusercontent.com/assets/7081026/7029543/ab622906-dd5e-11e4-951d-16faa51fe7f3.png)

Use meet-up log-in at (3):

![screen shot 2015-04-08 at 22 08 18](https://cloud.githubusercontent.com/assets/7081026/7054273/b6fe6d1e-de3b-11e4-9572-b2f135277b13.png)

SIgn up  meet up

![Uploading Screen Shot 2015-04-08 at 22.13.33.png . . .]()

**Comment by barsukov** [comment]
Can we close it ?

**Comment by adriverhagen** [comment]
yes

**Comment by adriverhagen** [comment]
Actually welcoming message on home page has to change to this : 

" Shelfless is the community library, a place where you can find and share print books. "
