### ISSUE TITLE
Organize party shelfless dance

### ISSUE THREAD

**Issue by adriverhagen** [barsukov/shelfless#65]
1. duncan gonna propose life bands
2. date 08/08
3. dj for after life bands ?

**Comment by adriverhagen** [comment]
need to find a way to invite whole group

**Comment by adriverhagen** [comment]
party.
Date: 08/08
Location : home or outside ?
Goal : Connect community

Content : 
Live bands
DJ
Authors ?

**Comment by barsukov** [comment]
Yes it would be super cool to invite some literature club, and We need to think about flyers
